CREATE TABLE [dbo].[Message] (
    [ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(newid()),
	[SentDate] DATETIME DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
	[RoomID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[Room]([ID]) ON DELETE CASCADE,
	[UserID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[User]([ID]) ON DELETE SET NULL,
    [Text] NVARCHAR(255) NOT NULL
)