CREATE TABLE [dbo].[RoomJoin] (
    [RoomID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[Room]([ID]) ON DELETE CASCADE,
    [UserID] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[User]([ID]) ON DELETE CASCADE,
	[Role] INT NOT NULL, 
    [JoinedDate] DATETIME DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
	PRIMARY KEY (RoomID, UserID)
)