CREATE TABLE [dbo].[User] (
	[ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(newid()),
	[CreatedDate] DATETIME DEFAULT(CURRENT_TIMESTAMP) NOT NULL,
	[Email] VARCHAR(255) UNIQUE NOT NULL,
	[Password] VARCHAR(60) NOT NULL,
	[Name] NVARCHAR(32) NOT NULL,
)