'use client'

import './globals.css'
import { Roboto_Flex as Font } from 'next/font/google'
import { SessionProvider } from 'next-auth/react'

const font = Font({ weight: ['400', '600', '700'], subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
}

export default function RootLayout({ children, session }: { children: React.ReactNode; session: any }) {
    return (
        <html lang="en">
            <body className={font.className}>
                <SessionProvider session={session}>{children}</SessionProvider>
            </body>
        </html>
    )
}
