CREATE TABLE [dbo].[Room] (
    [ID] UNIQUEIDENTIFIER PRIMARY KEY DEFAULT(newid()),
    [Owner] UNIQUEIDENTIFIER FOREIGN KEY REFERENCES [dbo].[User]([ID]) ON DELETE CASCADE,
    [Name] NVARCHAR(64) NOT NULL
)